#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.

menuentry "Arch" {
    # === CONFIGURABLE VARIABLES ===
    set isofile="/OS/cachyos-desktop-linux-250713.iso" # ISO file location.
    set partition="(hd0,3)" # 0 means first device, 3rd means partition
    set isodevice="/dev/sda3" # Partition where ISO is located.
    set kernel_path="/arch/boot/x86_64/vmlinuz-linux-cachyos" # Kernel file
    set initrd_path="/arch/boot/x86_64/initramfs-linux-cachyos.img" # initial RAM filesystem
 
    # === BOOT SETUP ===
    loopback loop $partition$isofile
    # === Arch ===
    linux (loop)$kernel_path img_dev=$isodevice img_loop=$isofile rw earlymodules=loop \
        cow_spacesize=4G copytoram \
        quiet loglevel=0 systemd.show_status=0 rd.udev.log_level=0 splash vt.global_cursor_default=0
    initrd (loop)$initrd_path
}

menuentry "Ubuntu/Debian" {
    # === CONFIGURABLE VARIABLES ===
    set isofile="/ubuntu.iso"
    set partition="(hd0,3)"
    set kernel_path="/casper/vmlinuz"
    set initrd_path="/casper/initrd"
 
    # === BOOT SETUP ===
    loopback loop $partition$isofile
    # === Ubuntu/Debian ===
    linux (loop)$kernel_path boot=casper iso-scan/filename=$isofile noeject noprompt splash --
    initrd (loop)$initrd_path
}
